// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SizeClassStats } from "./SizeClassStats";

export type BufferPoolStats = { totalAlloc: number, totalReturn: number, totalWaste: number, allocErrors: number, sizeClasses: Array<SizeClassStats>, };
