// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsPollutedEntry } from "./DnsPollutedEntry";

export type DnsPollutionStats = { totalChecked: number, pollutedCount: number, pollutionRate: number, recentPolluted: Array<DnsPollutedEntry>, };
