// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsQueryStats = { total: number, success: number, failed: number, avgLatencyUs: number, maxLatencyUs: number, };
