// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsServerClassification = { address: string, protocol: string, trustLevel: string, encrypted: boolean, description?: string | null, };
