// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsServerStats = { server: string, queries: number, successes: number, failures: number, avgLatencyUs: number, lastQuery: string, lastError?: string | null, };
