// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerfStats = { goroutines: number, gogc: number, memLimit: number, heapAlloc: number, heapSys: number, heapInUse: number, stackInUse: number, numGc: number, gcPauseTotal: number, protectedConns: number, ruleVersion: string, };
