// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuleExtra = { disabled: boolean, deleted: boolean, hitCount: number, hitAt: string, missCount: number, missAt: string, };
