// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rule } from "./Rule";

export type Rules = { rules: Array<Rule>, total?: number, page?: number, page_size?: number, };
