// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleExtra } from "./RuleExtra";
import type { RuleType } from "./RuleType";

export type Rule = { index: number, type: RuleType, payload: string, proxy: string, size: number, source: string, extra?: RuleExtra, };
