// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnTrafficSnapshot = { connId: string, metadata: string, proxyChain: string, upload: number, download: number, rateUp: number, rateDown: number, createdAt: string, lastActive: number, };
