// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsCacheStats } from "./DnsCacheStats";
import type { DnsPollutionStats } from "./DnsPollutionStats";
import type { DnsQueryStats } from "./DnsQueryStats";
import type { DnsServerStats } from "./DnsServerStats";
import type { DnsTrustSummary } from "./DnsTrustSummary";

export type DnsMetrics = { cache: DnsCacheStats, queries: DnsQueryStats, servers: Array<DnsServerStats>, pollution: DnsPollutionStats, trust: DnsTrustSummary, };
