// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsPollutedEntry = { domain: string, ip: string, timestamp: string, reason: string, };
