// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsQueryEvent = { domain: string, qType: string, server: string, protocol: string, proxyName?: string | null, proxyChain?: string | null, egress?: string | null, rule?: string | null, rulePayload?: string | null, success: boolean, error?: string | null, latencyUs: number, timestamp: string, };
