// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsServerStats = { server: string, queries: bigint, successes: bigint, failures: bigint, avgLatencyUs: bigint, lastQuery: string, lastError?: string | null, };
