// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsServerClassification } from "./DnsServerClassification";

export type DnsTrustSummary = { total: bigint, encrypted: bigint, unencrypted: bigint, byTrustLevel: { [key in string]?: bigint }, servers: Array<DnsServerClassification>, leakRiskScore: number, lastEvaluated: string, };
