// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EgressStatus = { stable: boolean, changeCount: number, observedCount?: number, egressIp?: string, remoteDestination?: string, proxyName?: string, proxyChain?: string, destinationAsn?: string, asnOrg?: string, rule?: string, rulePayload?: string, updatedAt?: string, };
